name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Extract metadata
        shell: bash
        run: |
          echo "GIT_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "BUILD_MODE=debug" >> $GITHUB_ENV
      - name: Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_STATS_WEBSITE_ID: ${{ vars.VITE_DEV_STATS_WEBSITE_ID }}
          VITE_GIT_SHA: ${{ env.GIT_SHA_SHORT }}
          VITE_BUILD_MODE: ${{ env.BUILD_MODE }}
        with:
          includeDebug: true
          tauriScript: pnpm tauri
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: RocketLaunchpad-windows
          path: |
            src-tauri/target/release/*.exe
            src-tauri/target/release/*.dll
            src-tauri/target/release/*.pdb
          retention-days: 90
