name: Publish

on:
  push:
    tags: [ "v*" ]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version variable
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v',''
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$version"
          Write-Host "Version: $version"
        shell: pwsh
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
        
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish -c Release /p:Version=$env:VERSION /p:NuGetVersion=$env:VERSION --self-contained true --no-restore -o dist\out
        shell: pwsh
      - name: Remove language files
        run: Get-ChildItem dist\out -Directory | Remove-Item -Recurse -Force
        shell: pwsh
      - name: Zip Release
        run: Compress-Archive -Path dist\out\* -DestinationPath dist\RocketLaunchpad-$env:VERSION.zip
        shell: pwsh
        
      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.3
        with: 
          nsis-version: "3.11"
      - name: Create NSIS installer
        run: |
          (Get-Content dist\installer.nsi) -replace '\$\(VERSION\)', $env:VERSION | Set-Content "dist\installer.nsi"
          makensis dist\installer.nsi
        shell: pwsh
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          overwrite_files: true
          draft: false
          files: dist/RocketLaunchpad-${{ env.VERSION }}-Setup.exe,dist/RocketLaunchpad-${{ env.VERSION }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}