name: Publish

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version variable
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/v',''
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$version"
          Write-Host "Version: $version"
        shell: pwsh
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
        
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish -c Release /p:Version=$env:VERSION /p:NuGetVersion=$env:VERSION --self-contained true --no-restore -o out
        shell: pwsh
      - name: Remove language files
        run: Get-ChildItem out -Directory | Remove-Item -Recurse -Force
        shell: pwsh
      - name: Zip Release
        run: Compress-Archive -Path out\* -DestinationPath RocketLaunchpad-$env:VERSION.zip
        shell: pwsh
        
      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.3
        with: 
          nsis-version: "3.11"
      - name: Create NSIS installer
        run: |
          @"
          OutFile "RocketLaunchpad-$env:VERSION-Setup.exe"
          InstallDir "$PROGRAMFILES\RocketLaunchpad"
          Section
            SetOutPath "$INSTDIR"
            File /r "out/*"
            CreateShortCut "$DESKTOP\RocketLaunchpad.lnk" "$INSTDIR\RocketLaunchpad.exe"
          SectionEnd
          "@ > installer.nsi
          makensis installer.nsi
        shell: pwsh
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RocketLaunchpad-${{ env.VERSION }}-Setup.exe
            RocketLaunchpad-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}